### ISSUE TITLE
Email activation link

### ISSUE THREAD

**Issue by Helfull** [matrixdevuk/6t9.me#1]
The email activation link doesn't look clickable

the first time you get the email you are kind of "forced" to click the button

**Comment by matrixdevuk** [comment]
Already working on making the email template a call-to-action. This should be fixed shortly.

Thanks :+1:

**Comment by matrixdevuk** [comment]
After the extremely long wait, I finally completed this issue. Had exams and crap to deal with and forgot about this issue pretty much.

Sorry about that. :)
