### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Helfull** [matrixdevuk/6t9.me#4]
from cope99:
Is this a desired behaviour ? https://www.6t9.me/public/index.php

from fourohhfour
Although /assets causes a redirect loop which is kinda weird

from helfull
/u is a bad link?
helfull [3:28 PM]3:28
why not redirect to /u/{user}

**Comment by matrixdevuk** [comment]
1: I'll have to work out a way to fix that
2: Weird... I'll check that out
3: I'll get that sorted shortly.

**Comment by matrixdevuk** [comment]
1. Fixed
2. Still checking it out
3. Done

**Comment by matrixdevuk** [comment]
All fixed.

**Comment by matrixdevuk** [comment]
#2 is going to be ignored for now.
